version: '3.7'
services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - app_backend
    volumes:
      - "./:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

  backend_1:
    container_name: backend_1
    build: .
    networks:
      - app_rabbitmq
      - app_backend
    volumes:
      - "./:/app"

  backend_2:
    container_name: backend_2
    build: .
    networks:
      - app_rabbitmq
      - app_backend
    volumes:
      - "./:/app"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    networks:
      - app_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env

networks:
  app_rabbitmq:
    driver: bridge
  app_backend:
    driver: bridge
